#!/bin/sh
# FireWall rules to run on system startup
#

#vars
WAN_IFACE="eth0"
LAN_IFACE="eth1"
DMZ_IFACE="eth2"

case "$1" in
 start)
 	echo "Starting FW"
	echo "1" > /proc/sys/net/ipv4/ip_forward
	iptables -t nat -F POSTROUTING
	iptables -F FORWARD
	iptables -F INPUT
	iptables -F OUTPUT
	iptables -P INPUT DROP
	iptables -P OUTPUT DROP
	iptables -P FORWARD DROP
	iptables -A FORWARD -o $WAN_IFACE -j ACCEPT
	iptables -A FORWARD -i $LAN_IFACE -o $DMZ_IFACE -j ACCEPT
	iptables -A FORWARD -i $LAN_IFACE -o $WAN_IFACE -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p icmp -o $LAN_IFACE -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p udp -o $WAN_IFACE --dport 53 -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p tcp -o $WAN_IFACE --dport 53 -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p tcp -o $WAN_IFACE --dport 80 -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p tcp -o $WAN_IFACE --dport 443 -j ACCEPT
	iptables -A FORWARD -i $DMZ_IFACE -p icmp -o $WAN_IFACE -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p icmp -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p udp --dport 53 -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 53 -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 80 -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 443 -j ACCEPT
	iptables -A OUTPUT -o $WAN_IFACE -p tcp --dport 22 -j ACCEPT
	iptables -A INPUT -p tcp -s 192.168.118.0/24 --dport 2222 -j ACCEPT
	iptables -A INPUT -p tcp -s 172.20.118.0/24 --dport 2222 -j ACCEPT
	iptables -A INPUT -p tcp -d 10.3.4.28 --dport 2222 -j ACCEPT
	iptables -A FORWARD -i $WAN_IFACE -p tcp -o $DMZ_IFACE --dport 22 -j ACCEPT
	iptables -t nat -A POSTROUTING -o $WAN_IFACE -j MASQUERADE
	iptables -A FORWARD -i $WAN_IFACE -p udp -o $DMZ_IFACE --dport 53 -j ACCEPT
	iptables -A FORWARD -i $WAN_IFACE -p tcp -o $DMZ_IFACE --dport 53 -j ACCEPT
	iptables -t nat -A PREROUTING -i $WAN_IFACE -p udp --dport 53 -j DNAT --to-destination 172.20.118.100:53
	iptables -t nat -A PREROUTING -i $WAN_IFACE -p tcp --dport 53 -j DNAT --to-destination 172.20.118.100:53
	iptables -t nat -A PREROUTING -i $WAN_IFACE -p tcp --dport 22 -j DNAT --to-destination 172.20.118.100:22
	iptables -A FORWARD -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
	iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
 	;;
 stop)
	echo "Stopping FW"
	iptables -t nat -F POSTROUTING
	iptables -F FORWARD
	iptables -F INPUT
	iptables -F OUTPUT
	;;
 restart|reload)
	$0 stop
 	$0 start
 	;;
 *)
	 echo "Usage: $0 {start|stop|restart|reload}"
 	exit 1
	;;
esac
exit 0
